### ISSUE TITLE
Redis is used for?

### ISSUE THREAD

**Issue by AkarshSatija** [rgallagher27/node-restify-oauth2-mongodb#3]
Hi, I just wish to ask you why and for what purpose are you using redis in this. Can you help me setting this up without REDIS?

**Comment by gmaniac** [comment]
There are quite a few reasons for using redis, but for this app all it is using it for is to pull the token out of the session instead of having to access the db every time a request is received.

To use this app without redis shouldn't be too difficult. You will have to remove it from the `package.json` line 22 and 23. Then replace Configs/hooks.js with this gist.
https://gist.github.com/gmaniac/56cd554f9415f8eb30ca

**Comment by gmaniac** [comment]
Also, I have added a pull request that you may want to use and make those changes listed above since this app does not work in its current state. You can comment in here or message me if you have any questions.

**Comment by AkarshSatija** [comment]
Thanks a lot @gmaniac.
